# This is a basic workflow to help you get started with Actions

name: DockerTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ demo ]

jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    #container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
     - name: check out code
       uses: actions/checkout@v2

    - name: Build docker images
      run: docker build -t local < ./Dockerfile
    - name: Run tests
      run: docker run local
